### ISSUE TITLE
Type of high dimensional data

### ISSUE THREAD

**Issue by mhmism** [YinanZheng/HIMA#4]
Thank you for this amazing package.
I would like to ask whether there are specific assumptions concerning the type/distribution of the omics mediator variables? For example, can the mediator be microbiome data (considering it is zero-inflated) and would you recommend a specific type of normalization?
The second question is concerning the exposure variable. Can I use it for a binary exposure variable (e.g. case/control study) where the variable is coded as 0 and 1?

Thank you in advance!

**Comment by YinanZheng** [comment]
Sorry for the delayed reply. Somehow GitHub did not send me a notification about the issues. For the microbiome data, the current HIMA package cannot do it. However, we are currently working on a new version of HIMA which will introduce a new function called "microHIMA" that is specifically designed for microbiome data mediation analysis. For the binary exposure, you can use it in all the HIMA family functions (including the upcoming microHIMA function). Please stay in tune. 

Best,
Yinan

**Comment by mhmism** [comment]
Thank you for your comment. I do see the microHIMA function has now been implemented. Is there away to measure the total indirect (mediation) effect besides the estimates of the individual taxa?

**Comment by YinanZheng** [comment]
> Thank you for your comment. I do see the microHIMA function has now been implemented. Is there away to measure the total indirect (mediation) effect besides the estimates of the individual taxa?

Thanks for your question. For the microHIMA, it is challenging to quantify total indirect effects. For other HIMA function applications, we can simply add the individual mediation effects to get a total effect. Unfortunately, this is not applicable for microHIMA. The reason is we used the ilr-based transformations on the compositional mediators. Hence, the estimated indirect effects are “relative effect” rather than “absolute effect” of the original compositional mediators.  So the summation of mediation effect of the individual taxa has no understandable meanings.
